-- files: opening, reading by format, writing, seeking, lines, pipes, the defaults
local function e(f, ...) local ok, m = pcall(f, ...) print(ok, m) end
local name = os.tmpname()
print(io.type(io.stdout), io.type(5), io.type(nil), type(io.stdout))
print(tostring(io.stdout):match("^file %(0x%x+%)$") ~= nil, io.stdout == io.output(), io.stdin == io.input())
local f = assert(io.open(name, "w"))
print(io.type(f), f:write("hello\n", 42, " ", 1.5, "\n", "last") == f)
print(f:close(), io.type(f), tostring(f))
e(function() return f:read() end)
e(function() return f:write("x") end)
print(pcall(f.close, f))
print(io.open("/nonexistent/dir/file", "r"))
e(function() return io.open(name, "rz") end)
e(function() return io.open(name, "q") end)
f = assert(io.open(name, "r"))
print(f:read("l"), f:read("n"), f:read("n"), f:read("l"), f:read("l"), f:read("l"))
f:close()
f = assert(io.open(name))
print(f:read("L"), f:read(2), f:read(0), f:read("a"), f:read("a"), f:read(0), f:read(1), f:read("l"))
f:close()
f = assert(io.open(name))
print(f:read("n", "l", "L"))
print(f:seek("set"), f:read(5), f:seek("cur"), f:seek("end"), f:seek("set", 6), f:read("l"), f:seek())
e(function() return f:seek("middle") end)
e(function() return f:read("x") end)
e(function() return f:read({}) end)
print(f:setvbuf("no"), f:setvbuf("full", 1024), f:flush())
e(function() return f:setvbuf("sometimes") end)
f:close()
local lines = {}
for l in io.lines(name) do lines[#lines + 1] = l end
print(#lines, lines[1], lines[2], lines[3])
for a, b in io.lines(name, 1, "l") do print(a, b) end
f = assert(io.open(name))
for l in f:lines("L") do io.write("[", l, "]") end
print(io.type(f))
f:close()
e(function() for l in io.lines("/nonexistent/x") do end end)
local it = io.lines(name)
print(it(), it(), it(), it())
e(function() return it() end)
f = io.open(name, "a")
f:write("\nappended")
f:close()
f = io.open(name, "r+")
print(f:read("l"))
f:seek("set", 6)
f:write("HELLO")
f:seek("set")
print(f:read("a"))
f:close()
print(io.output():write("direct\n") == io.stdout)
io.write("a", 1, 2.5, "\n")
e(function() io.write({}) end)
e(function() io.write(nil) end)
print(io.read and true, io.lines and true, io.popen and true)
local p = io.popen("echo piped; exit 3")
print(p:read("a"))
print(p:close())
p = io.popen("cat > " .. name, "w")
p:write("through the pipe\n")
print(p:close())
print(io.open(name):read("a"))
e(function() return io.popen("true", "x") end)
local t = io.tmpfile()
t:write("temp"); t:seek("set"); print(t:read("a")); t:close()
print(io.close(), io.output():close())
io.output(name)
io.write("via default output")
io.close()
io.output(io.stdout)
io.input(name)
print(io.read("a"))
io.input():close()
e(function() return io.read() end)
io.input(io.stdin)
e(function() io.input("/nonexistent/x") end)
e(function() io.input(5) end)
print(getmetatable(io.stdin).__name, getmetatable(io.stdin).__index.read == io.stdin.read, rawequal(getmetatable(io.stdin), getmetatable(io.stdout)))
e(function() return getmetatable(io.stdin).__gc() end)
e(function() return io.stdin.read() end)
e(function() return io.stdin.read(5) end)
print(io.stdout:close())
print(string.format("%s", io.stdout):match("^file") ~= nil, #tostring(io.stdout) > 6)
print(io.stdout.x, pcall(function() io.stdout.x = 1 end))
os.remove(name)
