-- the os library: dates, the environment, files by name
local function e(f, ...) local ok, m = pcall(f, ...) print(ok, m) end
print(os.time({year = 2000, month = 1, day = 1, hour = 0, min = 0, sec = 0}) -
      os.time({year = 1999, month = 12, day = 31, hour = 0, min = 0, sec = 0}))
local t = {year = 2000, month = 13, day = 40, hour = 25}
local at = os.time(t)
print(t.year, t.month, t.day, t.hour, t.min, t.sec, t.wday, t.yday, type(t.isdst))
print(os.time(t) == at, os.time() - os.time(os.date("*t")) < 5)
e(function() return os.time({year = 2000, month = 1}) end)
e(function() return os.time({year = "x", month = 1, day = 1}) end)
e(function() return os.time({year = 2000.5, month = 1, day = 1}) end)
e(function() return os.time({year = 2^40, month = 1, day = 1}) end)
e(function() return os.time(5) end)
print(os.date("!%Y-%m-%d %H:%M:%S", 946684800))
print(os.date("!%c", 0))
print(os.date("!%x %X %p %j %U %w %y %%", 0))
print(os.date("!%A %a %B %b %d %e %D %F %H %I %M %S", 86400 * 40))
local d = os.date("!*t", 946684800)
print(d.year, d.month, d.day, d.hour, d.min, d.sec, d.wday, d.yday, d.isdst)
print(os.date("!%d/%m/%Y", os.time({year = 2024, month = 2, day = 29, hour = 12})) ~= nil)
e(function() return os.date("%Q") end)
e(function() return os.date("%Ez") end)
e(function() return os.date("%Ey", 0) ~= nil end)
e(function() return os.date({}) end)
e(function() return os.date("%Y", "x") end)
print(os.date("!%H", 3600 * 5), os.date("!%H", "18000"))
print(os.getenv("HOME") ~= nil, os.getenv("NO_SUCH_VARIABLE_HERE"))
print(os.difftime(10, 4), os.difftime(4, 10))
e(function() return os.difftime(10) end)
print(type(os.clock()), os.clock() >= 0)
local name = os.tmpname()
print(type(name), name:match("^/") ~= nil)
print(os.rename(name, name .. ".moved"))
print(os.remove(name .. ".moved"))
local ok, msg, code = os.remove(name .. ".moved")
print(ok, msg == name .. ".moved: No such file or directory", code)
print(select("#", os.remove("/nonexistent/dir/file")), (select(3, os.remove("/nonexistent/dir/file"))) > 0)
print(os.rename("/nonexistent/a", "/nonexistent/b"))
print(os.execute())
print(os.execute("exit 3"))
print(os.execute("true"))
print(os.setlocale(), os.setlocale("C"), os.setlocale("xx_YY"), os.setlocale(nil, "numeric"))
