-- table.sort with and without comparators, math functions, select, tostring.
local t = { 5, 2, 8, 1, 9, 3 }
table.sort(t)
print(table.concat(t, ","))
table.sort(t, function(a, b) return a > b end)
print(table.concat(t, ","))
local words = { "pear", "apple", "fig", "banana" }
table.sort(words)
print(table.concat(words, " "))
table.sort(words, function(a, b) return #a < #b end)
print(words[1], words[4])
local recs = { { n = "b", v = 2 }, { n = "a", v = 1 }, { n = "c", v = 3 } }
table.sort(recs, function(x, y) return x.v < y.v end)
print(recs[1].n, recs[2].n, recs[3].n)

print(math.floor(3.7), math.floor(-3.7), math.ceil(3.2), math.ceil(-3.2), math.floor(5))
print(math.abs(-3), math.abs(-3.5), math.abs(3))
print(math.max(1, 5, 3), math.min(1, 5, 3), math.max(2.5, 2), math.min(-1, -1.5))
print(math.sqrt(16), math.sqrt(2), math.huge, -math.huge)
print(math.tointeger(3.0), math.tointeger(3.5), math.tointeger("8"), math.tointeger("x"))
print(math.fmod(7, 3), math.fmod(-7, 3), math.fmod(7.5, 2))
print(math.modf(3.7), math.modf(-3.7))
print(math.ult(1, 2), math.ult(-1, 2), math.pi)
print(string.format("%.4f %.4f %.4f", math.sin(1), math.cos(1), math.exp(1)))
print(string.format("%.4f %.4f %.4f", math.log(10), math.log(8, 2), math.log(1000, 10)))
print(math.type(math.floor(2.5)), math.type(2^2), 7 // 2 * 2 + 7 % 2)
math.randomseed(42)
local r = math.random(1, 6)
print(r >= 1 and r <= 6, math.random() < 1, math.random(3) <= 3)

print(tostring(1/3), tostring(100), tostring(-0.0), tostring(1e300 * 1e10), 2^63, -(2^63))
print(255 // 16, 255 % 16, string.format("%02x", 255 % 16))
print(#{ 1, 2, 3, nil, 5 } >= 3, #{ n = 1 })
print(select("#", table.unpack({ 1, 2, 3 })), table.unpack({ 1, 2, 3 }, 2))
print(table.unpack({ 1, 2, 3 }, 2, 3))
local packed = table.pack(table.unpack({ "a", "b" }))
print(packed.n, packed[1], packed[2])
print(next({ 10 }))
print(type(next), type(math), type(math.pi), type(os.clock()), type(os.time()))
print(os.clock() >= 0, os.time() > 1600000000)
print(rawequal("a", "a"), rawequal(1, 1.0), rawequal({}, {}))
print(tostring(nil) .. "|" .. tostring(false))
print(string.format("%5.1f|%-8s|%3d", 2.345, "ab", 7))
print(string.format("%g %g %g %g", 1e-5, 123456789, 0.5, 100))
print(8 % 3.5, 2^-1, 10 // 4.0, 1e2, 5 // -2.0)
print(("%d"):format(42), ("x"):rep(3, ","))
