-- an argument not passed, against one passed as nil
local function e(f, ...) local ok, m = pcall(f, ...) print(m) end
e(function() return tonumber() end)
e(function() return tonumber(10, 16) end)
e(function() return select() end)
e(function() return rawlen() end)
e(function() return assert() end)
e(function() return pcall() end)
e(function() return xpcall(print) end)
e(function() return xpcall(print, 5) end)
e(function() return rawset({}, 1) end)
e(function() return rawget({}) end)
e(function() return math.max() end)
e(function() return math.tointeger() end)
e(function() return math.type() end)
e(function() return string.char(256) end)
e(function() return string.char(1, -1) end)
e(function() return coroutine.create() end)
e(function() return coroutine.resume() end)
e(function() return coroutine.wrap(5) end)
e(function() return coroutine.status(nil) end)
e(function() return coroutine.close() end)
e(function() local a = setmetatable({}, {__add = 34}); return a + 1 end)
e(function() local a = setmetatable({}, {__lt = {}}); return a > a end)
e(function() local a = setmetatable({}, {__len = 3}); return #a end)
e(function() local a = setmetatable({}, {__call = 5}); return a() end)
e(function() return "x" + 1 end)
e(function() return "3" | 1 end)
e(function() return ~"3" end)
e(function() local a = 2.0^100; return a << 2 end)
print(math.max(1), math.min(3, 1, 2), math.max("b", "a"))
print(tostring(setmetatable({}, {__tostring = function() return 5 end})))
print(select("#", assert(1, 2, 3)), assert(false ~= nil))
local main, ismain = coroutine.running()
print(type(main), ismain, coroutine.status(main))
print(coroutine.resume(main))
print(pcall(coroutine.close, main))
coroutine.wrap(function()
  print(coroutine.status(main), pcall(coroutine.close, main))
  local co, inner = coroutine.running()
  print(type(co), inner)
end)()
print(load(5), (select(2, load(5))):match('^%[string "5"%]') ~= nil)
print(math.min({}) ~= nil, math.max(2, 2.5))
