print(pcall(string.rep))
print(pcall(string.rep, "x"))
print(pcall(string.rep, "x", nil))
print(pcall(function() return string.rep("x") end))
print(pcall(function() return ("x"):rep() end))
print(pcall(function() return math.floor() end))
print(pcall(function() return table.concat() end))
print(pcall(function() return table.concat(nil) end))
print(pcall(function() return tostring() end))
print(pcall(function() return setmetatable(1, {}) end))
print(pcall(function() for i = "a", 2 do end end))
print(pcall(function() for i = 1, "b" do end end))
print(pcall(function() for i = 1, 2, "c" do end end))
print(pcall(function() for i = 1.5, 2, {} do end end))
print(pcall(function() return string.rep("x", 1.5) end))
print(pcall(function() return ("x"):rep(1.5) end))
print(pcall(print))
print(select("#", pcall(print)))
