print(dofile("lib_chunk.txt"))
print(dofile_ran)
local f = loadfile("lib_chunk.txt")
print(f("arg1"))
print(dofile_ran)
print(loadfile("nothere.txt"))
print(pcall(dofile, "nothere.txt"))
local g = loadfile("lib_chunk.txt", "t", { dofile_ran = 100 })
g()
print(dofile_ran)
