-- string.format over bytes: %q, %a precision, flags the reference checks, %s through metamethods
local function checkQ(v)
  local s = string.format("%q", v)
  local nv = load("return " .. s)()
  print(s, v == nv, math.type(v) == math.type(nv), math.type(v), math.type(nv))
end
checkQ("\0\0\1\255\u{234}")
checkQ(math.maxinteger)
checkQ(math.mininteger)
checkQ(math.pi)
checkQ(0.1)
checkQ(true)
checkQ(nil)
checkQ(false)
checkQ(math.huge)
checkQ(-math.huge)
checkQ(0.0)
checkQ(-0.0)
checkQ(2^63)
local m = setmetatable({}, {__tostring = function () return "hello" end, __name = "hi"})
print(string.format("%s %.10s", m, m))
getmetatable(m).__tostring = nil
print(string.format("%.4s", m))
print(string.format("%s|%5s|%q", 1, true, "x"), #string.format("%s", {}) > 7, string.format("%s", io.stdout):sub(1, 5))
print(string.format("%+.2A", 12), string.format("%.4A", -12), string.format("%.3a", 0), string.format("%.0a", 1.5), string.format("%.0a", 2.5), string.format("%.1a", 1.96875), string.format("%a", 1), string.format("% a", 0.5), string.format("%.13a", 0.1), string.format("%.15a", 0.1), string.format("%.2a", -0.0), string.format("%A", 1/0))
print(string.format("%#12o", 10), string.format("%#10x", 100), string.format("%#-17X", 100), string.format("%013i", -100), string.format("%2.5d", -100))
print(string.format("%.u", 0), string.format("%+#014.0f", 100), string.format("%-16c", 97), string.format("%+.3G", 1.5), string.format("%.0s", "alo"), string.format("%.s", "alo"))
print(string.format("% 1.0E", 100), string.format("% .1g", 2^10))
local aux = string.rep("0", 600)
for _, f in ipairs{"%100.3d", "%1"..aux..".3d", "%1.100d", "%10.1"..aux.."004d", "%t", "%10q", "%-10q", "%.1q", "%5c", "%d"} do print(f:sub(1,20), pcall(string.format, f, 10)) end
print(string.format("%5.2s|%-5s|%05d|%+d|% d|%x", "abc", "x", 42, 5, 5, -1))
print(string.format("%c%c%c", 1, 65, 255) == "\1A\255", #string.format("%5s|", "\xe1"), string.format("%s", "a\0b") == "a\0b", pcall(function() return string.format("%d", "x") end))
print(string.format("%q", 1/3), string.format("%q", math.mininteger), string.format("%-6s|%6s|", "ab", "cd"))
local x = "\"\xe1lo\"\n\\"
print(string.format("%q%s", x, x) == "\"\\\"\xe1lo\\\"\\\n\\\\\"\"\xe1lo\"\n\\")
print(pcall(string.rep, "aa", 1 << 30))
print(table.concat({}, "x", math.maxinteger, math.maxinteger - 1) == "", table.concat({[math.maxinteger] = "alo"}, "x", math.maxinteger, math.maxinteger), table.concat({}, "x", math.mininteger + 1, math.mininteger) == "")
