local function e(f, ...) local ok, m = pcall(f, ...) print(ok, m) end
local function hex(s) return (s:gsub(".", function(c) return string.format("%02x", c:byte()) end)) end
print(hex(string.pack("<i4", -2)), hex(string.pack(">i4", -2)), hex(string.pack("=i4", 1)))
print(hex(string.pack("b B h H", 1, 2, 3, 4)))
print(hex(string.pack("<I3 >I3", 0x010203, 0x010203)))
print(hex(string.pack("<j J", -1, 1)), hex(string.pack("T", 5)))
print(hex(string.pack("<f d n", 1.5, -2.25, 3)))
print(hex(string.pack("z s1 s2 c3", "ab", "xyz", "q", "hi")))
print(hex(string.pack("!8 b d", 1, 2.0)), string.packsize("!8 b d"), string.packsize("!4 b d"), string.packsize("b Xd"))
print(string.packsize("i16"), string.packsize("!16 b i16"), string.packsize(""))
print(string.unpack("<i4", string.pack("<i4", -2)))
print(string.unpack(">i16", string.pack(">i16", -3)))
print(string.unpack("<I16", string.pack("<I16", 3)))
print(string.unpack("z s1 c3", string.pack("z s1 c3", "ab", "xyz", "hi")))
print(string.unpack("f d n", string.pack("f d n", 1.5, -2.25, 3)))
print(string.unpack("b", "\255"), string.unpack("B", "\255"))
print(string.unpack("<i3", "\255\255\127"), string.unpack("<i3", "\0\0\128"))
print(string.unpack("i4", "\1\0\0\0\2\0\0\0", 5))
print(string.unpack("i4", "\1\0\0\0\2\0\0\0", -4))
print(string.unpack("!4 b d", string.pack("!4 b d", 7, 0.5)))
print(string.unpack("z", "hello\0world\0"))
print(string.unpack("x b", "\0\9"))
print(string.unpack("", "abc"), string.unpack("", "abc", 3), string.unpack("", "abc", 4))
e(function() return string.pack("i17", 1) end)
e(function() return string.pack("i0", 1) end)
e(function() return string.pack("q", 1) end)
e(function() return string.pack("c", "x") end)
e(function() return string.pack("!3 d", 1) end)
e(function() return string.pack("b", 128) end)
e(function() return string.pack("B", 256) end)
e(function() return string.pack("i2", -32769) end)
e(function() return string.pack("i2", 32768) end)
e(function() return string.pack("i4") end)
e(function() return string.pack("i4", {}) end)
e(function() return string.pack("i4", 1.5) end)
e(function() return string.pack("i4", "x") end)
e(function() return string.pack("c2", "abc") end)
e(function() return string.pack("s1", string.rep("x", 256)) end)
e(function() return string.pack("z", "a\0b") end)
e(function() return string.pack("X", 1) end)
e(function() return string.pack("Xc1", 1) end)
e(function() return string.packsize("s") end)
e(function() return string.packsize("z") end)
e(function() return string.unpack("i4", "abc") end)
e(function() return string.unpack("z", "abc") end)
e(function() return string.unpack("i4", "abcd", 6) end)
e(function() return string.unpack("i9", "\0\0\0\0\0\0\0\0\1") end)
e(function() return string.unpack("s1", "\5ab") end)
e(function() return string.unpack("i4", "abcd", 0) end)
print(string.pack("i4", "10") == string.pack("i4", 10), string.pack("s1", 42) == "\2" .. "42")
print(#string.pack("!2 b d", 1, 1), #string.pack("!1 b d", 1, 1), #string.pack("! b d", 1, 1))
print(string.unpack(">I2", "\1\2"), string.unpack("<I2", "\1\2"))
print(math.type(string.unpack("d", string.pack("d", 3))), math.type(string.unpack("j", string.pack("j", 3))))
print(string.pack("<i1", -1):byte(), select("#", string.unpack("bbb", "\1\2\3")))
