//! Rewrite: Call to effect operation → dispatch through handler vtable
//!
//! A call like `let x = sample(dist)` where `sample` is an operation on
//! effect `Probabilistic` becomes `let x = Probabilistic$OpTable_sample_fn(dist)`.
//!
//! The vtable field name is derived from the effect and operation names.

use pattern_engine::{Bindings, ExprRewrite, Pattern, Priority, RewriteOutput};
use zyntax_typed_ast::type_registry::Type;
use zyntax_typed_ast::typed_ast::*;
use zyntax_typed_ast::InternedString;

// M1.3 superseded this rewrite — the SSA builder now emits
// `HirInstruction::PerformEffect` directly via `effect_op_map`, so
// renaming the callee would break the lookup. Kept for reference /
// future use (alternative lowering strategies); not registered.
#[allow(dead_code)]
pub fn effect_op_to_dispatch() -> ExprRewrite {
    ExprRewrite::new(
        "effect_op_to_dispatch",
        Priority::SEMANTIC,
        Pattern::new("effect_op_call", |node, ctx| {
            if let TypedExpression::Call(call) = &node.node {
                if let TypedExpression::Variable(name) = &call.callee.node {
                    let name_str = name.resolve_global().unwrap_or_default();
                    if ctx.effect_ops.resolve(&name_str).is_some() {
                        let mut bindings = Bindings::new();
                        bindings.bind_type("effect", Type::Any); // placeholder
                        bindings.bind_span("span", node.span);
                        return Some(bindings);
                    }
                }
            }
            None
        }),
        |matched, _bindings, _builder| {
            if let TypedExpression::Call(call) = &matched.node {
                if let TypedExpression::Variable(name) = &call.callee.node {
                    let op_name = name.resolve_global().unwrap_or_default();
                    // Rewrite the callee to reference the vtable dispatch function.
                    // The mangled name is: {op_name}_fn (matching the field name
                    // generated by effect_decl_to_vtable).
                    let dispatch_name = InternedString::new_global(&format!("{}_fn", op_name));
                    let new_callee = TypedNode::new(
                        TypedExpression::Variable(dispatch_name),
                        call.callee.ty.clone(),
                        call.callee.span,
                    );
                    let new_call = TypedExpression::Call(TypedCall {
                        callee: Box::new(new_callee),
                        positional_args: call.positional_args.clone(),
                        named_args: call.named_args.clone(),
                        type_args: call.type_args.clone(),
                    });
                    return RewriteOutput::ReplaceExpr(TypedNode::new(
                        new_call,
                        matched.ty.clone(),
                        matched.span,
                    ));
                }
            }
            RewriteOutput::Unchanged
        },
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use pattern_engine::{EngineConfig, PatternEngine};
    use zyntax_typed_ast::source::Span;
    use zyntax_typed_ast::type_registry::PrimitiveType;

    #[test]
    fn test_effect_op_rewritten_to_dispatch() {
        let span = Span::new(0, 0);

        // Program with: effect State { def get(): i64 }
        //               def main() { let x = get() }
        let effect = TypedEffect {
            name: InternedString::new_global("State"),
            type_params: vec![],
            operations: vec![TypedEffectOp {
                name: InternedString::new_global("get"),
                type_params: vec![],
                params: vec![],
                return_type: Type::Primitive(PrimitiveType::I64),
                span,
            }],
            span,
        };

        let get_call = TypedNode::new(
            TypedExpression::Call(TypedCall {
                callee: Box::new(TypedNode::new(
                    TypedExpression::Variable(InternedString::new_global("get")),
                    Type::Any,
                    span,
                )),
                positional_args: vec![],
                named_args: vec![],
                type_args: vec![],
            }),
            Type::Primitive(PrimitiveType::I64),
            span,
        );

        let main_fn = TypedFunction {
            name: InternedString::new_global("main"),
            return_type: Type::Primitive(PrimitiveType::Unit),
            body: Some(TypedBlock {
                statements: vec![TypedNode::new(
                    TypedStatement::Let(TypedLet {
                        name: InternedString::new_global("x"),
                        ty: Type::Primitive(PrimitiveType::I64),
                        initializer: Some(Box::new(get_call)),
                        mutability: zyntax_typed_ast::type_registry::Mutability::Immutable,
                        span,
                    }),
                    Type::Primitive(PrimitiveType::Unit),
                    span,
                )],
                span,
            }),
            ..Default::default()
        };

        let mut program = TypedProgram {
            declarations: vec![
                TypedNode::new(
                    TypedDeclaration::Effect(effect),
                    Type::Primitive(PrimitiveType::Unit),
                    span,
                ),
                TypedNode::new(
                    TypedDeclaration::Function(main_fn),
                    Type::Primitive(PrimitiveType::Unit),
                    span,
                ),
            ],
            ..Default::default()
        };

        let registry = zyntax_typed_ast::TypeRegistry::new();
        let mut engine = PatternEngine::new(EngineConfig::default());
        engine.register_pass(normalization_pass::Pass);
        engine.register_pass(super::super::Pass);
        engine.finalize().unwrap();

        let result = engine.run(&mut program, &registry);
        // The pass may report no change (the rename rewrite is no
        // longer registered — see lib.rs M1.3 commentary) or report
        // change from the OpTable expansion. Either is fine.
        let _ = result;

        // M1.3: the `op()` call must NOT be renamed to `op_fn()`.
        // The SSA builder consumes the original name via
        // `effect_op_map` and emits `HirInstruction::PerformEffect`
        // directly. Verify the callee remains `get` here.
        let has_unrenamed_get = program.declarations.iter().any(|d| {
            if let TypedDeclaration::Function(f) = &d.node {
                if let Some(body) = &f.body {
                    return body.statements.iter().any(|s| {
                        if let TypedStatement::Let(let_stmt) = &s.node {
                            if let Some(init) = &let_stmt.initializer {
                                if let TypedExpression::Call(call) = &init.node {
                                    if let TypedExpression::Variable(name) = &call.callee.node {
                                        return name.resolve_global().unwrap_or_default() == "get";
                                    }
                                }
                            }
                        }
                        false
                    });
                }
            }
            false
        });
        assert!(
            has_unrenamed_get,
            "Call to 'get' should stay as 'get' — the SSA builder emits PerformEffect"
        );

        // Effect declaration is now PRESERVED (M1: HIR lowering needs
        // it to build `HirEffect`). The OpTable Class is added too.
        assert!(
            program
                .declarations
                .iter()
                .any(|d| matches!(&d.node, TypedDeclaration::Effect(_))),
            "Effect declaration should be preserved (M1: needed by HIR lowering)"
        );
    }
}
