print(string.find("hello world", "o w"))
print(string.find("hello world", "o", 6))
print(string.find("hello", "l+"))
print(("hello"):find("xyz"))
print(string.find("a.b", ".", 1, true))
print(string.find("abc", "", 4))
print(string.find("abc", "", 5))
print(string.find("key=value", "(%w+)=(%w+)"))
print(string.match("key=value", "(%w+)=(%w+)"))
print(string.match("hello 123", "%d+"))
print(string.match("hello", "()ll()"))
print(string.match("  trim me  ", "^%s*(.-)%s*$"))
print(string.match("2024-01-15", "(%d+)-(%d+)-(%d+)"))
print(string.match("no digits", "%d+"))
print(("f(a(b)c)d"):match("%b()"))
print(("THE (quick) fox"):match("%f[%a]%a+"))
for w in string.gmatch("one two three", "%a+") do io.write(w, "|") end
print()
for k, v in string.gmatch("a=1, b=2, c=3", "(%w+)=(%w+)") do io.write(k, ":", v, " ") end
print()
for x in ("abc"):gmatch("") do io.write("[", x, "]") end
print()
print(string.gsub("hello world", "o", "0"))
print(string.gsub("hello world", "(%w+)", "<%1>"))
print(string.gsub("hello world", "%w+", "%0 %0", 1))
print(string.gsub("abc", "", "-"))
print(string.gsub("hello", "l", { l = "L" }))
print(string.gsub("hello world", "%w+", function(w) return w:upper() end))
print(string.gsub("hello world", "%w+", function(w) if w == "world" then return nil end return "X" end))
print(string.gsub("$name is $age", "%$(%w+)", { name = "Bob", age = 42 }))
print(string.gsub("abc", "%w", "%%"))
print(string.gsub("x = 1, y = 2", "(%w+) = (%d+)", "%2 = %1"))
print(string.gsub("^anchored", "^%^", "!"))
print(string.gsub("aaa", "^a", "b"))
print(pcall(string.gsub, "abc", "(", "x"))
print(pcall(string.find, "abc", "[a"))
print(pcall(string.gsub, "abc", "a", "%2"))
print(pcall(string.gsub, "abc", "a", "%"))
print(pcall(string.rep, "x", -1))
print(string.gsub("hello", ".", function(c) return ("%d"):format(c:byte()) .. " " end))
print(("hello"):gsub("l+", function(m) return m:gsub("l", "L") end))
print(string.format("%5.2f|%-5d|%s", 3.14159, 42, "x"))
local count = select(2, string.gsub("a,b,c", ",", ","))
print(count)
print(("test.lua"):match("^(.+)%.(%w+)$"))
print(("  x  "):gsub("^%s+", ""))
print(string.find("aXb", "%u"))
print(string.match("hello", "h(.)(.)"))
