local function e(f, ...) print(pcall(f, ...)) end
e(os.date, "%")
e(os.date, "%9")
e(os.date, "%O")
e(os.date, "%E")
e(os.date, "%Ea")
e(os.time, {year=1000, month=1, day=1, hour="x"})
e(os.time, {year=1000, month=1, day=1, hour=1.5})
e(os.time, {hour = 12})
print(os.date("\0\0") == "\0\0", #os.date(string.rep("a", 10000)), os.date(string.rep("%", 200)) == string.rep("%", 100))
print(os.time({year=2000,month=1,day=1}), os.time({year = -(1 << 31) + 1899, month = 1, day = 1}))
