//! Compile the API's C half into `libzl_capi.a`, and list the names
//! the executable exports: every `LUA_API` and `LUALIB_API` function
//! the vendored headers declare, and `lua_ident`.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

const HEADERS: [&str; 3] = ["lua.h", "lauxlib.h", "lualib.h"];

/// The function names a header declares with one of the API markers:
/// `LUA_API type (name) (params);`.
fn declared(text: &str) -> Vec<String> {
    let mut names = Vec::new();
    for line in text.lines() {
        let line = line.trim_start();
        let rest = match line
            .strip_prefix("LUA_API")
            .or_else(|| line.strip_prefix("LUALIB_API"))
        {
            Some(rest) if rest.starts_with([' ', '\t']) => rest,
            _ => continue,
        };
        let Some(open) = rest.find('(') else {
            continue;
        };
        let Some(close) = rest[open..].find(')') else {
            continue;
        };
        let name = rest[open + 1..open + close].trim();
        if !name.is_empty() && name.chars().all(|c| c.is_ascii_alphanumeric() || c == '_') {
            names.push(name.to_string());
        }
    }
    names
}

fn exports(vendor: &Path) -> Vec<String> {
    let mut names = Vec::new();
    for header in HEADERS {
        let path = vendor.join(header);
        println!("cargo:rerun-if-changed={}", path.display());
        let text = fs::read_to_string(&path).expect("a vendored header");
        names.extend(declared(&text));
    }
    names.push("lua_ident".to_string());
    names.sort();
    names.dedup();
    names
}

/// The table of every export's address, which keeps each one linked.
fn exports_rs(names: &[String]) -> String {
    let mut out = String::from(
        "// Generated by build.rs from the vendored headers.\n\
         #[allow(dead_code, clashing_extern_declarations, non_upper_case_globals)]\n\
         unsafe extern \"C\" {\n",
    );
    for name in names {
        if name == "lua_ident" {
            out.push_str("    static lua_ident: u8;\n");
        } else {
            out.push_str(&format!("    fn {name}();\n"));
        }
    }
    out.push_str("}\n\n");
    out.push_str(
        "/// Every exported name, sorted.\n\
         pub const EXPORT_NAMES: &[&str] = &[\n",
    );
    for name in names {
        out.push_str(&format!("    {name:?},\n"));
    }
    out.push_str("];\n\n");
    out.push_str(
        "#[allow(dead_code)]\n\
         pub struct Exports(pub [*const (); EXPORT_COUNT]);\n\
         // SAFETY: addresses of code and read-only data.\n\
         unsafe impl Sync for Exports {}\n\
         pub const EXPORT_COUNT: usize = ",
    );
    out.push_str(&names.len().to_string());
    out.push_str(
        ";\n\n/// The address of every export.\npub static EXPORTS: Exports = Exports([\n",
    );
    for name in names {
        if name == "lua_ident" {
            out.push_str("    &raw const lua_ident as *const (),\n");
        } else {
            out.push_str(&format!("    {name} as *const (),\n"));
        }
    }
    out.push_str("]);\n");
    out
}

fn main() {
    let root = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("the manifest's directory"));
    let out = PathBuf::from(env::var("OUT_DIR").expect("the output directory"));
    let vendor = root.join("vendor");
    let c = root.join("c");
    for f in [
        "c/lapi.c",
        "c/internal.h",
        "vendor/lauxlib.c",
        "vendor/luaconf.h",
    ] {
        println!("cargo:rerun-if-changed={}", root.join(f).display());
    }

    let names = exports(&vendor);
    let list = out.join("exports.txt");
    fs::write(&list, names.join("\n") + "\n").expect("the export list");
    fs::write(out.join("exports.rs"), exports_rs(&names)).expect("the export table");
    println!("cargo:exports={}", list.display());
    println!("cargo:include={}", vendor.display());

    if env::var("CARGO_CFG_TARGET_ARCH").as_deref() == Ok("wasm32") {
        return;
    }
    let native_include =
        env::var("DEP_ZRTL_NATIVE_INCLUDE").expect("zrtl_native's include directory");
    let mut build = cc::Build::new();
    build
        .file(c.join("lapi.c"))
        .file(vendor.join("lauxlib.c"))
        .include(&vendor)
        .include(&c)
        .include(native_include)
        .warnings(false)
        .cargo_metadata(false);
    if env::var("CARGO_CFG_TARGET_ENV").as_deref() != Ok("msvc") {
        build.flag_if_supported("-std=gnu99");
    }
    build.compile("zl_capi");
    println!("cargo:rustc-link-search=native={}", out.display());
    // Every member, whatever references it: the executable exports
    // these to libraries it opens, and an export list alone does not
    // pull an archive member into the link. Linked from here rather
    // than bundled into the rlib, so the objects' debug information
    // stays where the final link found it.
    println!("cargo:rustc-link-lib=static:+whole-archive,-bundle=zl_capi");
}
