//! Build script for zyntax_cli
//!
//! This script auto-discovers runtime plugins and generates registration code.
//! Frontend implementers simply need to add their runtime crate as a dependency
//! in Cargo.toml, and this build script will automatically register it.

use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());

    // Parse Cargo.toml to find runtime dependencies
    let cargo_toml =
        fs::read_to_string(manifest_dir.join("Cargo.toml")).expect("Failed to read Cargo.toml");

    let mut runtime_plugins = Vec::new();

    // Simple parser - look for dependencies that end with "_runtime"
    for line in cargo_toml.lines() {
        let trimmed = line.trim();
        if let Some(dep_name) = trimmed.strip_suffix("_runtime = {") {
            if dep_name.contains("zyntax") {
                runtime_plugins.push(dep_name.trim().to_string());
            }
        } else if let Some(dep_name) = trimmed.strip_suffix("_runtime = \"") {
            if dep_name.contains("zyntax") {
                runtime_plugins.push(dep_name.trim().to_string());
            }
        }
    }

    // Generate plugin registry code
    let registry_code = generate_plugin_registry(&runtime_plugins);

    fs::write(out_dir.join("plugin_registry.rs"), registry_code)
        .expect("Failed to write plugin_registry.rs");

    println!("cargo:rerun-if-changed=Cargo.toml");
}

fn generate_plugin_registry(plugins: &[String]) -> String {
    let mut code = String::from(
        "//! Auto-generated plugin registry\n\
         //! DO NOT EDIT - Generated by build.rs\n\n\
         use zyntax_compiler::plugin::PluginRegistry;\n\n\
         pub fn create_default_registry() -> PluginRegistry {\n\
         \x20   let mut registry = PluginRegistry::new();\n\n",
    );

    for plugin in plugins {
        code.push_str(&format!(
            "    // Register {} plugin\n\
             \x20   if let Some(plugin) = {}::get_plugin() {{\n\
             \x20       registry.register(plugin).expect(\"Failed to register {} plugin\");\n\
             \x20   }}\n\n",
            plugin, plugin, plugin
        ));
    }

    code.push_str("    registry\n}\n");

    code
}
